# Site settings
title: Spruce
email: hello@spruce.sh
description: > # this means to ignore newlines until "baseurl:"
  Spruce is a Continuous Integration and Delivery platform that enables you to ship
  code faster and with higher quality than ever before!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spruce.sh" # the base hostname & protocol for your site
twitter_username: sprucedev
github_username:  sprucedev

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      "categories": "blog"